In [44]:
import pandas as pd
import numpy as np

In [45]:
ufc_fighters = pd.read_csv('ufc_fighters.csv')
ufc_fighters

,Unnamed: 0,Name,Nickname,Record,Streak,Height,Weight,Reach,Stance,DOB,...,Sig_Str_Acc,Sig_Str_Abs_M,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg,Wins,Losses,Draws(NC)
0,0,Tom Aaron,NaN,Record: 5-3-0,-1,0,155.0,NaN,NaN,"Jul 13, 1978",...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,5,3,0
1,1,Rolando Dy,Dy Incredible,Record: 9-7-1 (1 NC),-1,68,145.0,69.0,Orthodox,"Aug 11, 1990",...,0.37,4.47,0.52,0.30,0.20,0.68,0.0,9,7,1 (1 NC)
2,2,Solomon Hutcherson,King,Record: 11-7-0 (1 NC),-1,71,185.0,NaN,Southpaw,"Aug 31, 1972",...,0.39,2.59,0.64,3.53,1.00,0.00,0.0,11,7,0 (1 NC)
3,3,Gleidson Cutis,Poney,Record: 7-4-0,-1,69,155.0,NaN,Orthodox,"Feb 07, 1989",...,0.52,8.28,0.59,0.00,0.00,0.00,0.0,7,4,0
4,4,Sean Brady,NaN,Record: 16-1-0,0,70,170.0,72.0,Orthodox,"Nov 23, 1992",...,0.53,3.55,0.61,3.29,0.57,0.87,1.2,16,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3767,3767,Zach Underwood,NaN,Record: 13-7-0,1,74,185.0,NaN,NaN,--,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,13,7,0
3768,3768,Hector Urbina,El Toro,Record: 17-10-1,-2,71,170.0,73.0,Orthodox,"Sep 17, 1987",...,0.38,2.44,0.39,0.00,0.00,0.38,3.8,17,10,1
3769,3769,Kengo Ura,Uraken,Record: 14-12-2,-1,69,165.0,NaN,NaN,"Jun 20, 1981",...,0.37,2.38,0.48,2.85,0.28,0.50,1.4,14,12,2
3770,3770,Scott Ventimiglia,Meant to Kill Ya,Record: 14-6-1,-1,71,185.0,NaN,NaN,"Nov 17, 1972",...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,14,6,1
3771,3771,Takeru Uchida,NaN,Record: 6-1-0,1,65,125.0,68.0,Southpaw,"Sep 30, 2002",...,0.00,0.00,0.00,0.00,0.00,0.00,4.4,6,1,0

In [46]:
ufc_fighters.dtypes

Unnamed: 0         int64
Name              object
Nickname          object
Record            object
Streak             int64
Height             int64
Weight           float64
Reach            float64
Stance            object
DOB               object
Sig_Str_M        float64
Sig_Str_Acc      float64
Sig_Str_Abs_M    float64
Str_Def          float64
TD_Avg           float64
TD_Acc           float64
TD_Def           float64
Sub_Avg          float64
Wins               int64
Losses             int64
Draws(NC)         object
dtype: object

In [47]:
ufc_fighters = ufc_fighters.drop(['Nickname'], axis=1)

In [48]:
ufc_fighters.isna().sum()

Unnamed: 0          0
Name                0
Record              0
Streak              0
Height              0
Weight             62
Reach            1569
Stance            474
DOB                 0
Sig_Str_M           0
Sig_Str_Acc         0
Sig_Str_Abs_M       0
Str_Def             0
TD_Avg              0
TD_Acc              0
TD_Def              0
Sub_Avg             0
Wins                0
Losses              0
Draws(NC)           0
dtype: int64

In [49]:
# Add age in Days Column
ufc_fighters['DOB'] = pd.to_datetime(ufc_fighters['DOB'], errors='coerce')
ufc_fighters['age_d'] = (pd.Timestamp('today') - ufc_fighters['DOB']).dt.days
ufc_fighters

,Unnamed: 0,Name,Record,Streak,Height,Weight,Reach,Stance,DOB,Sig_Str_M,...,Sig_Str_Abs_M,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg,Wins,Losses,Draws(NC),age_d
0,0,Tom Aaron,Record: 5-3-0,-1,0,155.0,NaN,NaN,1978-07-13,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,5,3,0,16850.0
1,1,Rolando Dy,Record: 9-7-1 (1 NC),-1,68,145.0,69.0,Orthodox,1990-08-11,3.04,...,4.47,0.52,0.30,0.20,0.68,0.0,9,7,1 (1 NC),12438.0
2,2,Solomon Hutcherson,Record: 11-7-0 (1 NC),-1,71,185.0,NaN,Southpaw,1972-08-31,2.59,...,2.59,0.64,3.53,1.00,0.00,0.0,11,7,0 (1 NC),18992.0
3,3,Gleidson Cutis,Record: 7-4-0,-1,69,155.0,NaN,Orthodox,1989-02-07,2.99,...,8.28,0.59,0.00,0.00,0.00,0.0,7,4,0,12988.0
4,4,Sean Brady,Record: 16-1-0,0,70,170.0,72.0,Orthodox,1992-11-23,3.77,...,3.55,0.61,3.29,0.57,0.87,1.2,16,1,0,11603.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3767,3767,Zach Underwood,Record: 13-7-0,1,74,185.0,NaN,NaN,NaT,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,13,7,0,NaN
3768,3768,Hector Urbina,Record: 17-10-1,-2,71,170.0,73.0,Orthodox,1987-09-17,0.97,...,2.44,0.39,0.00,0.00,0.38,3.8,17,10,1,13497.0
3769,3769,Kengo Ura,Record: 14-12-2,-1,69,165.0,NaN,NaN,1981-06-20,1.05,...,2.38,0.48,2.85,0.28,0.50,1.4,14,12,2,15777.0
3770,3770,Scott Ventimiglia,Record: 14-6-1,-1,71,185.0,NaN,NaN,1972-11-17,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,14,6,1,18914.0
3771,3771,Takeru Uchida,Record: 6-1-0,1,65,125.0,68.0,Southpaw,2002-09-30,0.00,...,0.00,0.00,0.00,0.00,0.00,4.4,6,1,0,8005.0

In [50]:
ufc_fighters.dtypes

Unnamed: 0                int64
Name                     object
Record                   object
Streak                    int64
Height                    int64
Weight                  float64
Reach                   float64
Stance                   object
DOB              datetime64[ns]
Sig_Str_M               float64
Sig_Str_Acc             float64
Sig_Str_Abs_M           float64
Str_Def                 float64
TD_Avg                  float64
TD_Acc                  float64
TD_Def                  float64
Sub_Avg                 float64
Wins                      int64
Losses                    int64
Draws(NC)                object
age_d                   float64
dtype: object

In [51]:
categorical_columns = ['Stance']
ufc_fighters = pd.get_dummies(ufc_fighters, columns=categorical_columns)
ufc_fighters.dtypes

Unnamed: 0                     int64
Name                          object
Record                        object
Streak                         int64
Height                         int64
Weight                       float64
Reach                        float64
DOB                   datetime64[ns]
Sig_Str_M                    float64
Sig_Str_Acc                  float64
Sig_Str_Abs_M                float64
Str_Def                      float64
TD_Avg                       float64
TD_Acc                       float64
TD_Def                       float64
Sub_Avg                      float64
Wins                           int64
Losses                         int64
Draws(NC)                     object
age_d                        float64
Stance_Open Stance              bool
Stance_Orthodox                 bool
Stance_Sideways                 bool
Stance_Southpaw                 bool
Stance_Switch                   bool
dtype: object

In [52]:
stats_columns = ['Streak', 'Height', 'Weight', 'Reach', 'Sig_Str_M', 'Sig_Str_Acc',
                'Sig_Str_Abs_M', 'Str_Def', 'TD_Avg', 'TD_Acc', 'TD_Def', 'Sub_Avg', 'Wins', 'Losses',
                'age_d', 'Stance_Open Stance','Stance_Orthodox', 'Stance_Sideways', 'Stance_Southpaw',
                 'Stance_Switch']

In [53]:
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import StandardScaler

ufc_fighters = ufc_fighters.dropna()

scaler = StandardScaler()

X_scaled = scaler.fit_transform(ufc_fighters[stats_columns])

In [54]:
ufc_fighters.isna().sum()

Unnamed: 0            0
Name                  0
Record                0
Streak                0
Height                0
Weight                0
Reach                 0
DOB                   0
Sig_Str_M             0
Sig_Str_Acc           0
Sig_Str_Abs_M         0
Str_Def               0
TD_Avg                0
TD_Acc                0
TD_Def                0
Sub_Avg               0
Wins                  0
Losses                0
Draws(NC)             0
age_d                 0
Stance_Open Stance    0
Stance_Orthodox       0
Stance_Sideways       0
Stance_Southpaw       0
Stance_Switch         0
dtype: int64

In [55]:
# Compute the pairwise distance matrix
distance_matrix = pairwise_distances(X_scaled, metric='euclidean')

# Convert the distance matrix to a DataFrame for better readability
distance_df = pd.DataFrame(distance_matrix, index=ufc_fighters['Name'], columns=ufc_fighters['Name'])

# Display the pairwise distance matrix
distance_df

Name,Rolando Dy,Sean Brady,Kennedy Nzechukwu,Cristiane Justino,Lisa Kyriacou,Mike Kyle,Cristian Quinonez,Dong Hyun Ma,Leah Letson,Jose Quinonez,...,Timur Valiev,Richie Vaculik,Elias Urbina,Gilbert Urbina,Kevin Vallejos,Logan Urban,Nick Urso,Caol Uno,Hector Urbina,Takeru Uchida
Name,,,,,,,,,,,,,,,,,,,,,
Rolando Dy,0.000000,3.961627,5.976081,4.570656,2.827744,5.156931,2.192313,2.780206,3.950620,4.444105,...,3.126913,3.202737,5.577825,4.940068,5.311591,7.951334,4.990012,6.616414,4.937567,9.717027
Sean Brady,3.961627,0.000000,5.662696,3.494904,5.165393,5.045448,3.097642,4.316596,4.744895,4.582215,...,3.318303,3.594922,6.646304,4.430899,6.232367,8.883221,6.850193,7.485038,6.010971,11.059520
Kennedy Nzechukwu,5.976081,5.662696,0.000000,6.699331,7.412660,5.374401,5.752401,5.896679,4.605302,5.272156,...,6.508204,6.754582,4.340572,5.524386,7.139979,9.089503,6.763512,7.486454,7.201873,11.117082
Cristiane Justino,4.570656,3.494904,6.699331,0.000000,5.108485,5.712432,3.833548,5.188630,5.508839,5.414808,...,3.246966,4.445907,7.682349,5.880279,6.623121,10.086919,6.957204,7.509659,7.314795,12.062934
Lisa Kyriacou,2.827744,5.165393,7.412660,5.108485,0.000000,7.081046,3.575312,4.529049,4.848619,5.082169,...,3.064890,3.730022,5.836484,5.158663,5.029521,7.699617,4.196023,7.918300,6.056570,9.367956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Logan Urban,7.951334,8.883221,9.089503,10.086919,7.699617,9.337534,8.437306,8.437161,8.927107,9.518946,...,8.246561,8.408984,7.470713,7.227490,8.496025,0.000000,7.733646,11.193542,9.273227,12.634620
Nick Urso,4.990012,6.850193,6.763512,6.957204,4.196023,7.444555,5.824005,5.640561,4.285753,4.421349,...,4.962702,5.120867,4.551790,6.099493,6.122669,7.733646,0.000000,6.386030,6.582807,8.487334
Caol Uno,6.616414,7.485038,7.486454,7.509659,7.918300,5.546833,6.983258,5.610900,6.604476,5.789354,...,6.685203,6.525460,8.081167,8.132601,8.973303,11.193542,6.386030,0.000000,6.623755,11.177000
Hector Urbina,4.937567,6.010971,7.201873,7.314795,6.056570,5.371412,5.746220,4.959920,6.666065,6.554925,...,5.816681,5.412865,6.913487,6.139743,7.684668,9.273227,6.582807,6.623755,0.000000,8.136005
Takeru Uchida,9.717027,11.059520,11.117082,12.062934,9.367956,11.830578,10.401610,10.523079,9.268029,9.895823,...,10.231463,10.295230,9.456069,10.625812,10.459308,12.634620,8.487334,11.177000,8.136005,0.000000

In [56]:
np.fill_diagonal(distance_matrix, np.inf)

In [57]:
distance_df.to_csv('fighter_alike_distance.csv')

In [60]:

def find_alike(name):
    """

    :param Name: Name of fighter
    :return: prints a list of alike fighters if the fighter exist
    """

    fighter = distance_df[distance_df.index.str.contains(name, case=False)]
    if not fighter.empty:
        fighter_name = fighter.index[0]
        fighter_distances = distance_df.loc[fighter_name]
        closest_fighters = fighter_distances.sort_values().iloc[1:21]
        print(f"Closest fighters to {fighter_name}:")
        print(closest_fighters)
    else:
        print(f"No fighter found matching the name '{name}'.")

In [61]:
merab_alike = find_alike(distance_df, 'Merab')

AttributeError: Can only use .str accessor with string values!

In [84]:
omalley_alike = find_alike('O\'Malley')

Closest fighters to Sean O'Malley:
Name
Manuel Torres        2.752987
Brendan Loughnane    2.757946
Petr Yan             2.951586
Hyder Amil           2.976898
Anshul Jubli         3.048385
Dricus Du Plessis    3.067712
Kevin Syler          3.089402
Vinicius Oliveira    3.098510
Evan Elder           3.133437
Charles Johnson      3.172488
Charles Jourdain     3.180350
Rafael Fiziev        3.182887
Daniel Zellhuber     3.200825
Jack Jenkins         3.201094
Kaiwen               3.266116
Bill Algeo           3.327563
Trevor Peek          3.329673
Billy Ray Goff       3.333186
Victor Altamirano    3.367643
John Castaneda       3.398583
Name: Sean O'Malley, dtype: float64

In [ ]:
def compare_fighters(df, f1, f2):
    """
    Compare two fighters and return the distance (similarity) between them.

    :param df: DataFrame of fighter pairwise distances.
    :param f1: Name of the first fighter.
    :param f2: Name of the second fighter.
    :return: Distance between the two fighters or an error message.
    """
    # Ensure the index is of string type
    df.index = df.index.astype(str)

    # Ensure f1 and f2 are in the dataset
    if f1 in df.index and f2 in df.columns:
        distance = df.loc[f1, f2]
        return distance
    else:
        return 'One or both fighters were not found in the dataset.'